// Shared types for the application

export type Page =
  | 'login'
  | 'register'
  | 'client-dashboard'
  | 'gerant-dashboard'
  | 'livreur-dashboard'
  | 'livreur_missions'
  | 'livreur_history'
  | 'gerant_history'
  | 'admin_history'
  | 'admin-dashboard'
  | 'profile'
  | 'tracking'
  | 'shipping'
  | 'shipping-confirmation'
  | 'mandate'
  | 'mandate-confirmation'
  | 'history'
  | 'admin/users'
  | 'admin/agences'
  | 'admin/colis'
  | 'admin/mandats'
  | 'admin/reports'
  | 'admin/settings'
  | 'manage_shipments'
  | 'manage_mandates'
  | 'assign_couriers'
  | 'view_reports';
